name: carnd-term1-gpu
channels:
  - defaults
dependencies:
  - scipy
  - black
  - imageio
  - parso=0.7
  - matplotlib
  - pillow
  - jupyter
  - pyqt
  - pylint
  - python=3.6
  - pandas
  - seaborn
  - flask-socketio
  - ffmpeg
  - h5py
  - scikit-image
  - prompt_toolkit=2
  - numpy
  - cudatoolkit=8
  - pip
  - eventlet
  - scikit-learn
  - python-engineio==3.13.2
  - python-socketio==4.6.1
  - decorator==4.4.2
