name: carnd-term1-gpu
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.6
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - pyqt
    - parso=0.7
    - prompt_toolkit=2
    - black
    - pylint
    - cudatoolkit=8
    - python-engineio==3.13.2
    - python-socketio==4.6.1
    - pip
    - pip:
        - moviepy==1.0.3
        - opencv-python
        - requests
        - tensorflow-gpu==1.3.0
        - keras==2.0.9
        - decorator==4.4.2